# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3151cb55c92d255b78a3075a91b1c5393246d0f182e005f51c1f11fdd53fb4397a5e6b6356eb106612f5ffe4891a0db21958444e556da59f76a1089166ff6f9

test:
  secret_key_base: 3223eab47a13f5e70e7f66fb33008b831222fe899534a496a436c499ed233b170869d869b020b9b2a561fe139657b54b2173171b0ab9449935cdef8ed597dbde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
